### ISSUE TITLE
World Editor App

### ISSUE THREAD

**Issue by Hayjw916** [Rasmodius-10101/Goose-Art-Offline#2]
After looking at how the worlds work, I think I have a good idea of how they work and it's a semi good system. Anyways, I don't want to edit the format of how the world file is structured. 

I want to create an app that makes creating and managing these files easier so if you want to create a new world, you can do so from a gui so you can structure it and see what it looks like before you use it in the game. It would make level editing way easier while also making it easier for new people who are maybe wanting to make new levels for the game.

**Comment by Rasmodius-10101** [comment]
Great Idea Glad I had it
